# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "."
    puppet.manifest_file = "vagrant.pp"
  end
end
